#!/bin/sh
# sh ./bootstrap 	>>/tmp/build-$PTARGET.log
# sh ./autogen		>>/tmp/build-$PTARGET.log
# cp .prev-version .version
autoreconf -i >> /tmp/build-$PTARGET.log
autoreconf -i >> /tmp/build-$PTARGET.log
sh ./configure \
	--build=$LT_ARCH \
	--host=$CCT \
	--target=$CCT \
	--prefix=$PREFIX \
	--disable-debug \
	--disable-locale \
	--disable-doc \
	--disable-man \
	--disable-manual \
	--disable-nls \
	>> /tmp/build-$PTARGET.log
exit
###################################
