#!/bin/sh
sh ./bootstrap
# sh ./autogen		>>/tmp/build-$PTARGET.log
# autoreconf -i 	>>/tmp/build-$PTARGET.log
# autoreconf -i 	>>/tmp/build-$PTARGET.log
sh ./configure \
	--host=$CCT \
	--with-sysroot=$SYSROOTMOUNT \
	--build=$LT_ARCH \
	--target=$CCT \
	--prefix=$PREFIX \
	--disable-debug \
	--disable-locale \
	--disable-doc \
	--disable-man \
	--disable-manual \
	--disable-nls

exit
###################################
