#!/bin.sh
sed -i '' -e "s/git/$COMMIT/" RELEASE
sh ./configure \
	--prefix=/usr/local \
	--disable-debug \
	--disable-debug \
	--disable-manpages \
	--disable-doc \
	--enable-shared \
	--enable-cross-compile \
	--cc=$CC

exit
#
#--build=$LT_ARCH \
#--host=$CCT \
#--target=$CCT \
#cross_compiling=yes
