#!/bin/sh
rm -rf /tmp/gnulib-master
tar -C /tmp -xvf $BSD_CONTRIB/___legacy/gnulib
export GNULIB_SRCDIR="/tmp/gnulib-master"
sh ./bootstrap \
	--skip-git \
	--skip-po \
	--verbose \
	--gnulib-srcdir=/tmp/gnulib-master
sh ./configure \
	--prefix=/usr/local \
	--program-prefix=g
