#!/bin/sh
sh ./auto/configure \
	--host=$CCT \
	--with-sysroot=$SYSROOTMOUNT \
	--prefix=/usr \
	--disable-debug \
	--prefix=/usr/local \
	--conf-path=/etc/app/nginx/nginx.conf \
	--pid-path=/var/run/nginx.pid \
	--with-zlib \
	--with-http_gzip_static_module \
	--with-openssl \
	--with-http_ssl_module \
	--with-stream_ssl_module

#		--http-log-path=/var/pnoc/http/nginx-access.log		\
#		--error-log-path=/var/pnoc/http/nginx-error.log		\
#		--http-client-body-temp-path=temp/client_body_temp	\
#		--http-proxy-temp-path=/var/proxy_temp			\
#		--http-fastcgi-temp-path=/var/proxy_temp/fastcgi_temp	\
#		--http-scgi-temp-path=/var/proxy_temp/scgi_temp		\
#		--http-uwsgi-temp-path=temp/uwsgi_temp			\
#		--with-cc-opt=-DFD_SETSIZE=1024				\
#		--with-pcre=$(OBJS)/lib/$(PCRE)				\
#		--with-zlib=$(OBJS)/lib/$(ZLIB)				\
#		--with-http_v2_module					\
#		--with-http_realip_module				\
#		--with-http_addition_module				\
#		--with-http_sub_module					\
#		--with-http_dav_module					\
#		--with-http_stub_status_module				\
#		--with-http_flv_module					\
#		--with-http_mp4_module					\
#		--with-http_gunzip_module				\
#		--with-http_gzip_static_module				\
#		--with-http_auth_request_module				\
#		--with-http_random_index_module				\
#		--with-http_secure_link_module				\
#		--with-http_slice_module				\
#		--with-mail						\
#		--with-stream						\
#		--with-openssl=$(OBJS)/lib/$(OPENSSL)			\
#		--with-openssl-opt="no-asm no-tests -D_WIN32_WINNT=0x0501" \
#		--with-http_ssl_module					\
#		--with-mail_ssl_module					\
#		--with-stream_ssl_module
