#!/bin/sh
(cd autoconf && autoconf configure.in > ../configure)
echo > autoconf/make/depend.mk~
echo > autoconf/make/filelist.mk~
echo > autoconf/make/modules.mk~
rm -rf .gen
mkdir .gen
cd .gen
sh ../configure \
	--build=$LT_ARCH \
	--host=$CCT \
	--target=$CCT \
	--prefix=/usr \
	cross_compiling=yes
$MAKE make
$MAKE dep
