#!/bin/sh
#ac_default_prefix=/usr
export VCOMMIT=$(cat .commit)
sed -i '' -e "s/2019 Dec 12/$VCOMMIT/g" src/version.h
sh ./configure \
	--build=$LT_ARCH \
	--host=$CCT \
	--target=$CCT \
	--prefix=/usr \
	--disable-darwin \
	--disable-smack \
	--disable-selinux \
	--disable-canberra \
	--disable-gtktest \
	--disable-icon-cache-update \
	--disable-desktop-database-update \
	--disable-gui \
	--disable-xsmp \
	--disable-xsmp-interact \
	--disable-netbeans \
	--disable-channel \
	--disable-rightleft \
	--disable-arabic \
	--disable-farsi \
	--disable-canberra \
	--disable-acl \
	--disable-gpm \
	--disable-sysmouse \
	--disable-nls \
	--without-local-dir \
	--with-features=normal \
	--enable-cscope \
	--enable-multibyte \
	--with-tlib=ncursesw \
	cross_compiling=yes \
	vim_cv_toupper_broken=yes \
	vim_cv_terminfo=yes \
	vim_cv_tgetent=no \
	vim_cv_getcwd_broken=yes \
	vim_cv_stat_ignores_slash=yes \
	vim_cv_memmove_handles_overlap=yes \
	vim_cv_timer_create=no \
	vim_cv_timer_create_with_lrt=yes
