#!/bin/sh
. $BSD_ARCH/amd64.amd64.x86-64-v2-avx
. $BSD_ARCH/.intel
export BSD_TARGET_SOC=ivybridge
export TARCH_L3=$SOC # sticking with x86-64-v2 would loose avx capability
export BSD_KERNCONF_DEVICE="$BSD_KERNCONF_DEVICE rdrand_rng aesni"
. $BSD_ARCH/.boot.amd64
